### ISSUE TITLE
Worst text centering ever

### ISSUE THREAD

**Issue by ziggi** [openmultiplayer/homepage#109]
Centering text other than headers is the worst idea ever.

# Fix for FAQ page
```css
.content {
    text-align: justify;
}
h2 {
    text-align: center;
}
```

Need to rework other pages too.

# How it looks now
![image](https://user-images.githubusercontent.com/1020099/59919766-046be900-9431-11e9-9117-07c10e15adc0.png)

# How it looks after the fix
![image](https://user-images.githubusercontent.com/1020099/59919664-b5be4f00-9430-11e9-94a7-ca930e25ee61.png)
